### ISSUE TITLE
Cryptic README.md - Change grahic

### ISSUE THREAD

**Issue by DevMimas** [cryptic-game/cryptic#26]
## Discription
Vorschlag: Die Grafik auf cryptic-game/cryptic/Readme.md verkleinern. Den grauen Rand wesentlich kleiner machen, mehr von der eigentlichen Grafik. Wenn einverstanden damit.
Fragen gerne an @DevMimas 

## Design
![grafik](https://user-images.githubusercontent.com/44207756/62654576-5f658b00-b960-11e9-8ae5-8ea99126147e.png)

**Comment by DevMimas** [comment]
@Chaozz66 würdest du dich drum kümmern wollen? Ist ein Vorschlag von mir.

**Comment by cadamini** [comment]
It does not hurt, maybe this should be closed.

**Comment by cadamini** [comment]
Wäre das Logo von der Webseite nicht eine Alternative? https://github.com/cryptic-game/website/blob/master/assets/icons/cryptic_head.svg

**Comment by cadamini** [comment]
@DevMimas see linked pull request

**Comment by DevMimas** [comment]
@cadamini Many thanks for your work.

**Comment by cadamini** [comment]
@MarcelCoding see linked PR
