### ISSUE TITLE
Update Credits-Document

### ISSUE THREAD

**Issue by DevMimas** [cryptic-game/cryptic#32]
# Description
Aktualisiere das Dokument.
Altes Dokument: [Credits-Dokument](https://docs.google.com/document/d/1eWpIHAYGDfy1BWfYB5_Zyocv8GfuvvutE0Sn7Oc4zJM/edit#heading=h.7uzootjlhnze)

Neues Dokument: [Credits-Dokument Wiki](https://wiki.cryptic-game.net/books/credits)

**Comment by felixevers** [comment]
Current state, please!

**Comment by DevMimas** [comment]
Wurde heute von @Defelo und @DevMimas aktualisiert
