### ISSUE TITLE
backend-introduction

### ISSUE THREAD

**Issue by tanneberger** [cryptic-game/cryptic#39]
Just an markdown file where we describe how the backend works. For beginners.

**Comment by DevMimas** [comment]
Was for the old backend in Pre alpha 2. Issue to be closed.

**Comment by Defelo** [comment]
> Was for the old backend in Pre alpha 2. Issue to be closed.

but still relevant for the new backend, therefore reopened

**Comment by JannikEmmerich** [comment]
Introduction to the Java-Backend can be found [here](https://wiki.cryptic-game.net/books/einf%C3%BChrungen/chapter/java) (WIP, DE)
