### ISSUE TITLE
Test-Server einrichten

### ISSUE THREAD

**Issue by DevMimas** [cryptic-game/cryptic#41]
## Discription
Es soll ein weiterer Server fürs Spiel eingerichtet werden, welcher nur für Testes genutzt wird. Neue Spielelemente sollen dort zuerst gestestet werden.
Läuft der Spielstand stabil, kommt dieser Teil auf den öffentlichen Spielserver.

**Comment by felixevers** [comment]
Done an available on https://play.test.cryptic-game.net/
