### ISSUE TITLE
Writing Workflow for Github

### ISSUE THREAD

**Issue by DevMimas** [cryptic-game/cryptic#42]
To summarize, write a process describing how to manage the issues in Github and how to handle each project.

**Comment by cadamini** [comment]
I am confused. Writing a workflow for Github or writing about the Github workflow?

I think this can be closed. General information about Github can be found in the docs: 
- [projects](https://docs.github.com/en/issues/organizing-your-work-with-project-boards/managing-project-boards/about-project-boards) 
- [issues](https://docs.github.com/en/issues/tracking-your-work-with-issues/about-issues)

**Comment by DevMimas** [comment]
Thank you for your comment. That was the idea at the time to explain the workflow of the project, how this works on Github.
I will close the issue.
