### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by DevMimas** [cryptic-game/cryptic#50]
## Description
Update the description, update some links and texts, maybe extend the description a little and make a new project structure

- delete the faq@cryptic-game.net is not in use

## Problem
Some things are out of date

**Comment by DevMimas** [comment]
delete the faq@cryptic-game.net is not in use

**Comment by cadamini** [comment]
Linked the stale PR which would close the issue.

**Comment by cadamini** [comment]
@DevMimas This can be closed as we merged the revised readme file.

**Comment by cadamini** [comment]
@MarcelCoding see my comment above. Can you close this issue?
