### ISSUE TITLE
Fix typos and missing commas in instruction

### ISSUE THREAD

**Issue by cadamini** [cryptic-game/cryptic#67]
**Describe the bug**
Fix typos and comma issues in https://wiki.cryptic-game.net/books/spielanleitung

**Reproduce**
One example (of many):

> a) ein Untermenü öffnet sich in dem du einen Hintergrund auswählen kannst 

https://wiki.cryptic-game.net/books/spielanleitung/page/einstellungen

**Comment by Tristan-H11** [comment]
Thank you for issuing these typos. It has been passed on and will be fixed.
